/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as ConfirmSimulationRouteImport } from './routes/confirm-simulation'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PinRouteImport } from './routes/pin'
import { Route as SuccessSimulatorRouteImport } from './routes/success-simulator'
import { Route as TransfersimulatorRouteImport } from './routes/transfersimulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSimulationRoute = ConfirmSimulationRouteImport.update({
  id: '/confirm-simulation',
  path: '/confirm-simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessSimulatorRoute = SuccessSimulatorRouteImport.update({
  id: '/success-simulator',
  path: '/success-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersimulatorRoute = TransfersimulatorRouteImport.update({
  id: '/transfersimulator',
  path: '/transfersimulator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/confirm-simulation': typeof ConfirmSimulationRoute
  '/home': typeof HomeRoute
  '/pin': typeof PinRoute
  '/success-simulator': typeof SuccessSimulatorRoute
  '/transfersimulator': typeof TransfersimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/confirm-simulation': typeof ConfirmSimulationRoute
  '/home': typeof HomeRoute
  '/pin': typeof PinRoute
  '/success-simulator': typeof SuccessSimulatorRoute
  '/transfersimulator': typeof TransfersimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/confirm-simulation': typeof ConfirmSimulationRoute
  '/home': typeof HomeRoute
  '/pin': typeof PinRoute
  '/success-simulator': typeof SuccessSimulatorRoute
  '/transfersimulator': typeof TransfersimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/confirm-simulation'
    | '/home'
    | '/pin'
    | '/success-simulator'
    | '/transfersimulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/confirm-simulation'
    | '/home'
    | '/pin'
    | '/success-simulator'
    | '/transfersimulator'
  id:
    | '__root__'
    | '/'
    | '/balance'
    | '/confirm-simulation'
    | '/home'
    | '/pin'
    | '/success-simulator'
    | '/transfersimulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceRoute: typeof BalanceRoute
  ConfirmSimulationRoute: typeof ConfirmSimulationRoute
  HomeRoute: typeof HomeRoute
  PinRoute: typeof PinRoute
  SuccessSimulatorRoute: typeof SuccessSimulatorRoute
  TransfersimulatorRoute: typeof TransfersimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-simulation': {
      id: '/confirm-simulation'
      path: '/confirm-simulation'
      fullPath: '/confirm-simulation'
      preLoaderRoute: typeof ConfirmSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-simulator': {
      id: '/success-simulator'
      path: '/success-simulator'
      fullPath: '/success-simulator'
      preLoaderRoute: typeof SuccessSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfersimulator': {
      id: '/transfersimulator'
      path: '/transfersimulator'
      fullPath: '/transfersimulator'
      preLoaderRoute: typeof TransfersimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceRoute: BalanceRoute,
  ConfirmSimulationRoute: ConfirmSimulationRoute,
  HomeRoute: HomeRoute,
  PinRoute: PinRoute,
  SuccessSimulatorRoute: SuccessSimulatorRoute,
  TransfersimulatorRoute: TransfersimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
